# Classification of Titanic passengers

- Let's load the dataset

In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

titanic_df = pd.read_csv('titanic.csv', index_col='PassengerId')
titanic_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


## Data processing & feature engineering

#### Data processing

Let's process the data according to the EDA from the 1st exercise.

In [2]:
from data_processing import process_data

titanic_df = process_data(titanic_df)
titanic_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
PassengerId,,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,2.110213,NoCabin,0,0,1
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,4.280593,C85,1,0,0
3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,2.188856,NoCabin,0,0,1
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,3.990834,C123,0,0,1
5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,2.202765,NoCabin,0,0,1

#### Feature engineering

Let's extract the features(Title, FamilySize, HasCabin, Deck) and remove remaining columns used to extract them

In [3]:
from feature_engineering import engineer_features

titanic_df = engineer_features(titanic_df)
titanic_df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Title,FamilySize,HasCabin,Deck_A,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_N,Deck_T
PassengerId,,,,,,,,,,,,,,,,,,,,,,
1,0,3,0,22.0,1,0,2.110213,0,0,1,Mr,2,0,0,0,0,0,0,0,0,1,0
2,1,1,1,38.0,1,0,4.280593,1,0,0,Mrs,2,1,0,0,1,0,0,0,0,0,0
3,1,3,1,26.0,0,0,2.188856,0,0,1,Miss,1,0,0,0,0,0,0,0,0,1,0
4,1,1,1,35.0,1,0,3.990834,0,0,1,Mrs,2,1,0,0,1,0,0,0,0,0,0
5,0,3,0,35.0,0,0,2.202765,0,0,1,Mr,1,0,0,0,0,0,0,0,0,1,0