In [1]:
from google.colab import drive # remove the cell if not using colab
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
base_path = Path('/content/drive/MyDrive/solvro_dane') # change path here!

# Klasyfikacja pasażerów Titanica
Nie wiemy czy dla DiCaprio było miejsce na drzwiach, ale wiemy że grdyby był tam Wojfer87 to by z nimi wyciskał pompki na górze lodowej. Teraz twoja pora na wyciskanie.
#Twoje zadnie to:
**stworzenie modelu przewidującego szanse przeżycia katastrofy Titanica**.

![https://i1.jbzd.com.pl/contents/2025/11/normal/v5Fth4DcPpPPxSrXQ5rCbAgZ8EifWiiF.png](https://i1.jbzd.com.pl/contents/2025/11/normal/v5Fth4DcPpPPxSrXQ5rCbAgZ8EifWiiF.png "Wojfer")


#### Twoim celem będzie jest wytrenowanie modeli do klasyfikacji każdego pasażera Titanica jako ofiary (0) lub osoby, która przeżyła (1).

Poniżej znajdziesz pytania, które mogą być pomocne w zadaniu:

- Czego nauczyło Cię o badanym zbiorze danych poprzednie zadanie? Jak możesz wykorzystać wyciągnięte z niego wnioski w procesie tworzenia modelu?
- Jak przeprowadzenie standaryzacji danych może wpływać na zachowanie modelu?
- Co mój model robi i w jaki sposób?
- Jak nie przetrenować wybranego modelu?
- Jaki wynik klasyfikacji możemy uznać za *dobry*?


Wymagania:
- Wypisz obserwacje z pierwszego zadania, które pomogą Ci w tym. Co było przydatne, a co okazało się bezużyteczne?
- [Nie doprowadź](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) do ~~przecieku statku~~ wycieku danych (np. nie ucz modelu na danych testowych). Nauczone modele odpal na danych treningowych i testowych - opisz uzyskane wyniki.
- Stwórz baseline, czyli dla porównania sprawdź jak z zadaniem radzi sobie [Dummy Classifier](https://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyClassifier.html) (jeśli Twój docelowy model radzi sobie gorzej - uciekaj)
- Przeprowadź badania na dwóch wybranych modelach uczenia maszynowego (np. spośród: drzew decyzyjnych, SVM, MLP, KNN, z gwiazdką [XGBoost](https://xgboost.readthedocs.io/en/stable))
- W badaniach użyj wybranych metryk. Wybór uzasadnij.
- Dla każdego modelu wybierz co najmniej dwa hiperparametry i przeprowadź badania zależności wyników metryk od wartości hiperparametrów. Zwizualizuj wszystko ładnie, zastanów się dlaczego tak mogło być i wyciągnij i wypisz wnioski.
- Podsumuj przeprowadzone badania, wypisz wnioski.

Niezmiennie, zadbaj o czytelność kodu i nazewnictwo zmiennych. Jeśli jakiś wycinek kodu się powtarza, to wyodrębnij go do funkcji. Postaraj się zamieszczać swoje wnioski w postaci komentarza `Markdown`.

Jeśli chcesz, możesz sprawdzić (przyjmując pewne założenia), jakie byłyby Twoje szanse na Titanicu.

Uwaga! Jeśli Titanic to dla Ciebie nic i baaaaardzo chcesz to możesz w ramach tego zadania zająć się [bardziej wymagającym](https://archive.ics.uci.edu/dataset/365/polish+companies+bankruptcy+data) zbiorem.

In [3]:
titanic_df = pd.read_csv(base_path / 'titanic_final.csv', index_col='PassengerId')

# Wnioski z EDA
Większą szansę na przeżycie miały:
* kobiety
* dzieci
* pasażerowie wyższych klas
* pasażerowie z przypisanymi kabinami (łączy się z klasą)

# Ładowanie i dzielenie danych

In [4]:
from sklearn.model_selection import train_test_split

X = titanic_df.drop(columns=['Survived'])
y = titanic_df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=.8, shuffle=True)

# Skalowanie danych

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Baseline - Dummy Classifier

In [6]:
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support, classification_report
from sklearn.dummy import DummyClassifier

model = DummyClassifier(strategy='most_frequent') # dane nie są zbalansowane - większość zginęła
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(classification_report(y_test, y_pred))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

           0       0.64      1.00      0.78       114
           1       0.00      0.00      0.00        65

    accuracy                           0.64       179
   macro avg       0.32      0.50      0.39       179
weighted avg       0.41      0.64      0.50       179

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

array([[114,   0],
       [ 65,   0]])

# Support Vector Machine

In [7]:
from sklearn.svm import SVC

svm = SVC(kernel='linear')  # liniowe SVM
svm.fit(X_train_scaled, y_train)

y_pred = svm.predict(X_test_scaled)

print(classification_report(y_test, y_pred))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       114
           1       0.74      0.74      0.74        65

    accuracy                           0.81       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.81      0.81      0.81       179

array([[97, 17],
       [17, 48]])

# Multi Layer Perceptron

In [8]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(max_iter=1000, random_state=42, hidden_layer_sizes=(64, 32), early_stopping=True)
mlp.fit(X_train_scaled, y_train)

y_pred = mlp.predict(X_test_scaled)

print(classification_report(y_test, y_pred))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

           0       0.84      0.81      0.83       114
           1       0.69      0.74      0.71        65

    accuracy                           0.78       179
   macro avg       0.76      0.77      0.77       179
weighted avg       0.79      0.78      0.78       179

array([[92, 22],
       [17, 48]])

# K Nearest Neighbors

In [9]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=10, metric='cosine')
knn.fit(X_train_scaled, y_train)

y_pred = knn.predict(X_test_scaled)

print(classification_report(y_test, y_pred))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

           0       0.82      0.88      0.85       114
           1       0.75      0.66      0.70        65

    accuracy                           0.80       179
   macro avg       0.79      0.77      0.78       179
weighted avg       0.80      0.80      0.80       179

array([[100,  14],
       [ 22,  43]])

W zależności od tego jak załadują się dane, modele dają znacząco różne wyniki.

# Cross-Validation

In [10]:
from sklearn.model_selection import cross_val_score

svm_score = cross_val_score(svm, X, y, cv=5, scoring='f1')
mlp_score = cross_val_score(mlp, X, y, cv=5, scoring='f1')
knn_score = cross_val_score(knn, X, y, cv=5, scoring='f1')

print('---------- SVM ----------')
print(svm_score)
print(f"srednia: {svm_score.mean():.3f}  odchylenie: {svm_score.std():.3f}")

print('\n---------- MLP ----------')
print(mlp_score)
print(f"srednia: {mlp_score.mean():.3f}  odchylenie: {mlp_score.std():.3f}")

print('\n---------- KNN ----------')
print(knn_score)
print(f"srednia: {knn_score.mean():.3f}  odchylenie: {knn_score.std():.3f}")

---------- SVM ----------
[0.7826087  0.76691729 0.75384615 0.70588235 0.82089552]
srednia: 0.766  odchylenie: 0.038

---------- MLP ----------
[0.38655462 0.55932203 0.50485437 0.59459459 0.56198347]
srednia: 0.521  odchylenie: 0.073

---------- KNN ----------
[0.58015267 0.64       0.59016393 0.61016949 0.60714286]
srednia: 0.606  odchylenie: 0.020

Wybrałem metrykę f1 - jest ona harmoniczną średnią z precision i recall. Model musi dobrze wybierać, ale też nie może się za często mylić. Z obecnymi parametrami dość często się myli.

In [11]:
!pip install optuna
import optuna
from sklearn.pipeline import Pipeline
import optuna.visualization as vis

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 8.4 MB/s eta 0:00:00
Downloading alembic-1.19.1-py3-none-any.whl (265 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 kB 20.6 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.19.1 colorlog-6.12.0 optuna-4.9.0

# Szukanie hiperparametrów dla SVM

In [12]:
def svm_search(trial):
  c_param = trial.suggest_float('C', 0.01, 100, log=True)

  kernel_param = trial.suggest_categorical('kernel', ['linear', 'rbf'])

  if kernel_param == 'rbf':
      gamma_param = trial.suggest_float('gamma', 0.0001, 10, log=True)
  else:
      gamma_param = 'scale'

  class_weight_param = trial.suggest_categorical('class_weight', [None, 'balanced'])

  svm = SVC(C=c_param, kernel=kernel_param, gamma=gamma_param,
            class_weight=class_weight_param, random_state=42)

  pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('svm', svm)
    ])

  score = cross_val_score(pipeline, X, y, cv=5, scoring='f1').mean()
  return score

study = optuna.create_study(direction='maximize')

study.optimize(svm_search, n_trials=100)

print("\n--- ZAKOŃCZONO ---")
print(f"Najlepszy F1: {study.best_value:.4f}")
print("Najlepsze parametry:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

[I 2026-08-17 10:13:56,856] A new study created in memory with name: no-name-915744a2-5ecc-42f3-9d4b-a85fcae1a622
[I 2026-08-17 10:13:57,325] Trial 0 finished with value: 0.7641497402364538 and parameters: {'C': 3.113956373389924, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:13:57,641] Trial 1 finished with value: 0.719355243412165 and parameters: {'C': 0.24738394854481321, 'kernel': 'rbf', 'gamma': 0.002319773479267346, 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:13:57,851] Trial 2 finished with value: 0.7548308255854559 and parameters: {'C': 0.47876771560482945, 'kernel': 'rbf', 'gamma': 0.4582955586642765, 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:13:58,069] Trial 3 finished with value: 0.7288546142308023 and parameters: {'C': 0.024048144542257684, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:13:58,527] Trial 4 finished with value: 0.0 and parameters: {'C': 0.033227683634360926, 'kernel': 'rbf', 'gamma': 0.0005561092791995781, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:06,813] Trial 5 finished with value: 0.762281405349327 and parameters: {'C': 42.07331588253984, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:07,424] Trial 6 finished with value: 0.7452013650395786 and parameters: {'C': 0.035829816854413096, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:09,710] Trial 7 finished with value: 0.7622868741159285 and parameters: {'C': 12.364902885888162, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:10,167] Trial 8 finished with value: 0.0 and parameters: {'C': 0.014175111810356363, 'kernel': 'rbf', 'gamma': 0.0033277532880022025, 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:10,873] Trial 9 finished with value: 0.33170731707317075 and parameters: {'C': 0.019522008633103882, 'kernel': 'rbf', 'gamma': 0.003940527568652416, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:12,016] Trial 10 finished with value: 0.762281405349327 and parameters: {'C': 3.4972877917693066, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:14,676] Trial 11 finished with value: 0.7622868741159285 and parameters: {'C': 16.34731540211775, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:16,021] Trial 12 finished with value: 0.7641497402364538 and parameters: {'C': 3.278228766760989, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:17,053] Trial 13 finished with value: 0.7629533294687569 and parameters: {'C': 1.6815085289469172, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:18,431] Trial 14 finished with value: 0.7641497402364538 and parameters: {'C': 2.1187767080961053, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:19,032] Trial 15 finished with value: 0.7629533294687569 and parameters: {'C': 0.4021783598662018, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:20,831] Trial 16 finished with value: 0.7641497402364538 and parameters: {'C': 7.202912820460063, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:32,912] Trial 17 finished with value: 0.7622868741159285 and parameters: {'C': 97.69132756508623, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:33,682] Trial 18 finished with value: 0.758811975572539 and parameters: {'C': 0.8827298121525239, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:33,893] Trial 19 finished with value: 0.7629533294687569 and parameters: {'C': 0.16895075684374464, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:34,109] Trial 20 finished with value: 0.761808427858739 and parameters: {'C': 0.12059887131688082, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:34,594] Trial 21 finished with value: 0.7641497402364538 and parameters: {'C': 2.7312001060469906, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:35,271] Trial 22 finished with value: 0.7641497402364538 and parameters: {'C': 5.494178563554286, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:35,616] Trial 23 finished with value: 0.7629533294687569 and parameters: {'C': 1.3458111177779544, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:36,753] Trial 24 finished with value: 0.7622868741159285 and parameters: {'C': 20.738149083002877, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:37,146] Trial 25 finished with value: 0.7641497402364538 and parameters: {'C': 3.3592991339416094, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:37,369] Trial 26 finished with value: 0.7024606484748649 and parameters: {'C': 0.8401550031050523, 'kernel': 'rbf', 'gamma': 5.208786790244355, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:38,016] Trial 27 finished with value: 0.7641497402364538 and parameters: {'C': 7.799716177962746, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:38,268] Trial 28 finished with value: 0.7641497402364538 and parameters: {'C': 2.0215739986971246, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:38,483] Trial 29 finished with value: 0.7339431689582979 and parameters: {'C': 32.87072348039416, 'kernel': 'rbf', 'gamma': 0.09100714651684642, 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:38,612] Trial 30 finished with value: 0.7582353839871876 and parameters: {'C': 0.08226651387125503, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:39,110] Trial 31 finished with value: 0.7641497402364538 and parameters: {'C': 6.572142003142711, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:39,720] Trial 32 finished with value: 0.7641497402364538 and parameters: {'C': 10.108105874208356, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:40,129] Trial 33 finished with value: 0.7641497402364538 and parameters: {'C': 4.603090420318133, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:40,321] Trial 34 finished with value: 0.0 and parameters: {'C': 0.48327879776254845, 'kernel': 'rbf', 'gamma': 0.00011264881115551718, 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:40,516] Trial 35 finished with value: 0.7629533294687569 and parameters: {'C': 0.9959736446408961, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:40,690] Trial 36 finished with value: 0.7577391786376731 and parameters: {'C': 0.495512595460211, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:40,936] Trial 37 finished with value: 0.7641497402364538 and parameters: {'C': 1.913431686878138, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:41,170] Trial 38 finished with value: 0.7360075343329436 and parameters: {'C': 24.821049244349787, 'kernel': 'rbf', 'gamma': 0.07173803043365148, 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:41,863] Trial 39 finished with value: 0.7641497402364538 and parameters: {'C': 11.80163968220406, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:44,285] Trial 40 finished with value: 0.762281405349327 and parameters: {'C': 54.03208201745612, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:44,572] Trial 41 finished with value: 0.7641497402364538 and parameters: {'C': 2.9555869271581696, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:44,853] Trial 42 finished with value: 0.7641497402364538 and parameters: {'C': 2.725124001843622, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:45,341] Trial 43 finished with value: 0.7641497402364538 and parameters: {'C': 6.7730531178543885, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:45,761] Trial 44 finished with value: 0.7641497402364538 and parameters: {'C': 4.355550537469107, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:46,114] Trial 45 finished with value: 0.7629533294687569 and parameters: {'C': 1.3447010247625577, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:46,512] Trial 46 finished with value: 0.6948412528449212 and parameters: {'C': 3.003303284056755, 'kernel': 'rbf', 'gamma': 5.864347141663861, 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:46,812] Trial 47 finished with value: 0.7577391786376731 and parameters: {'C': 0.7224034494034258, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:47,046] Trial 48 finished with value: 0.7629533294687569 and parameters: {'C': 0.31298199836765944, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:48,702] Trial 49 finished with value: 0.7641497402364538 and parameters: {'C': 15.120018871547371, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:49,194] Trial 50 finished with value: 0.7641497402364538 and parameters: {'C': 2.105509085863479, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:49,890] Trial 51 finished with value: 0.7641497402364538 and parameters: {'C': 5.241762081644393, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:50,660] Trial 52 finished with value: 0.7641497402364538 and parameters: {'C': 8.386997095465025, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:51,100] Trial 53 finished with value: 0.7641497402364538 and parameters: {'C': 5.264605320419014, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:51,474] Trial 54 finished with value: 0.7641497402364538 and parameters: {'C': 4.073197659701513, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:51,674] Trial 55 finished with value: 0.7629533294687569 and parameters: {'C': 1.0859733987001987, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:51,963] Trial 56 finished with value: 0.7641497402364538 and parameters: {'C': 2.525958810868838, 'kernel': 'linear', 'class_weight': None}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:52,174] Trial 57 finished with value: 0.7610715909571544 and parameters: {'C': 1.2799625522982307, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7641497402364538.
[I 2026-08-17 10:14:52,342] Trial 58 finished with value: 0.7701467415675095 and parameters: {'C': 1.7470416553203578, 'kernel': 'rbf', 'gamma': 0.034098617721104195, 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:52,513] Trial 59 finished with value: 0.7615091806558368 and parameters: {'C': 0.7266112241029391, 'kernel': 'rbf', 'gamma': 0.04541790108985845, 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:52,739] Trial 60 finished with value: 0.7287033588009596 and parameters: {'C': 9.234405348718973, 'kernel': 'rbf', 'gamma': 0.5547161728403256, 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:52,918] Trial 61 finished with value: 0.7621927794763976 and parameters: {'C': 1.6725662052719792, 'kernel': 'rbf', 'gamma': 0.01570216191524457, 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:53,138] Trial 62 finished with value: 0.7232584936437411 and parameters: {'C': 3.691330747856808, 'kernel': 'rbf', 'gamma': 0.8520073624042332, 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:53,305] Trial 63 finished with value: 0.702860171281746 and parameters: {'C': 15.244653785526086, 'kernel': 'rbf', 'gamma': 0.00011925088880174246, 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:53,801] Trial 64 finished with value: 0.7641497402364538 and parameters: {'C': 6.22080013254383, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:54,043] Trial 65 finished with value: 0.7629533294687569 and parameters: {'C': 1.6541434945443532, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:54,197] Trial 66 finished with value: 0.7571076891281494 and parameters: {'C': 2.3503765282118882, 'kernel': 'rbf', 'gamma': 0.009728411328970274, 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:54,493] Trial 67 finished with value: 0.7641497402364538 and parameters: {'C': 3.288033002709821, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:54,911] Trial 68 finished with value: 0.762281405349327 and parameters: {'C': 5.393902805430551, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:55,099] Trial 69 finished with value: 0.7641497402364538 and parameters: {'C': 0.6219761023302509, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:55,253] Trial 70 finished with value: 0.72017904861607 and parameters: {'C': 11.535251480311418, 'kernel': 'rbf', 'gamma': 0.0008434685170209821, 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:55,577] Trial 71 finished with value: 0.7641497402364538 and parameters: {'C': 4.027184312117677, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:55,851] Trial 72 finished with value: 0.7641497402364538 and parameters: {'C': 2.3220103005282717, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:56,397] Trial 73 finished with value: 0.7641497402364538 and parameters: {'C': 7.3660583375688145, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:56,628] Trial 74 finished with value: 0.7629533294687569 and parameters: {'C': 1.6247273166097316, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:56,928] Trial 75 finished with value: 0.7641497402364538 and parameters: {'C': 3.2829245002460596, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:57,157] Trial 76 finished with value: 0.7629533294687569 and parameters: {'C': 1.1288513339978414, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:58,436] Trial 77 finished with value: 0.7622868741159285 and parameters: {'C': 22.70252625746577, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:58,788] Trial 78 finished with value: 0.7641497402364538 and parameters: {'C': 4.766408502060907, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:58,923] Trial 79 finished with value: 0.7635019470575145 and parameters: {'C': 0.05158264658307252, 'kernel': 'linear', 'class_weight': 'balanced'}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:59,178] Trial 80 finished with value: 0.7641497402364538 and parameters: {'C': 1.8989242438768796, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:14:59,774] Trial 81 finished with value: 0.7641497402364538 and parameters: {'C': 8.330836782902054, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:15:00,244] Trial 82 finished with value: 0.7641497402364538 and parameters: {'C': 6.271430654419625, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:15:00,565] Trial 83 finished with value: 0.7641497402364538 and parameters: {'C': 2.81850445899133, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:15:02,462] Trial 84 finished with value: 0.7622868741159285 and parameters: {'C': 18.002045136300467, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:15:03,671] Trial 85 finished with value: 0.7622868741159285 and parameters: {'C': 11.061327076740254, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:15:04,291] Trial 86 finished with value: 0.7641497402364538 and parameters: {'C': 4.1137711971717605, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:15:04,646] Trial 87 finished with value: 0.7198234187291938 and parameters: {'C': 1.347511254947821, 'kernel': 'rbf', 'gamma': 1.9777120579969567, 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:15:05,177] Trial 88 finished with value: 0.7641497402364538 and parameters: {'C': 3.3191685775380164, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:15:05,800] Trial 89 finished with value: 0.7641497402364538 and parameters: {'C': 7.860431050839063, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:15:05,923] Trial 90 finished with value: 0.7055308704683061 and parameters: {'C': 0.010404577653404443, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.
[I 2026-08-17 10:15:06,191] Trial 91 finished with value: 0.7641497402364538 and parameters: {'C': 2.715981961750995, 'kernel': 'linear', 'class_weight': None}. Best is trial 58 with value: 0.7701467415675095.

--- ZAKOŃCZONO ---
Najlepszy F1: 0.7701
Najlepsze parametry:
  C: 1.7470416553203578
  kernel: rbf
  gamma: 0.034098617721104195
  class_weight: None

In [13]:
study.trials_dataframe().sort_values(by='value', ascending=False).head(10)

,number,value,datetime_start,datetime_complete,duration,params_C,params_class_weight,params_gamma,params_kernel,state
58,58,0.770147,2026-08-17 10:14:52.175721,2026-08-17 10:14:52.342833,0 days 00:00:00.167112,1.747042,None,0.034099,rbf,COMPLETE
0,0,0.764150,2026-08-17 10:13:56.858909,2026-08-17 10:13:57.325474,0 days 00:00:00.466565,3.113956,None,NaN,linear,COMPLETE
16,16,0.764150,2026-08-17 10:14:19.040585,2026-08-17 10:14:20.830896,0 days 00:00:01.790311,7.202913,None,NaN,linear,COMPLETE
12,12,0.764150,2026-08-17 10:14:14.682700,2026-08-17 10:14:16.021280,0 days 00:00:01.338580,3.278229,None,NaN,linear,COMPLETE
28,28,0.764150,2026-08-17 10:14:38.017161,2026-08-17 10:14:38.268082,0 days 00:00:00.250921,2.021574,None,NaN,linear,COMPLETE
31,31,0.764150,2026-08-17 10:14:38.613404,2026-08-17 10:14:39.110358,0 days 00:00:00.496954,6.572142,None,NaN,linear,COMPLETE
33,33,0.764150,2026-08-17 10:14:39.721577,2026-08-17 10:14:40.129115,0 days 00:00:00.407538,4.603090,None,NaN,linear,COMPLETE
32,32,0.764150,2026-08-17 10:14:39.111666,2026-08-17 10:14:39.720385,0 days 00:00:00.608719,10.108106,None,NaN,linear,COMPLETE
25,25,0.764150,2026-08-17 10:14:36.754486,2026-08-17 10:14:37.146370,0 days 00:00:00.391884,3.359299,None,NaN,linear,COMPLETE
27,27,0.764150,2026-08-17 10:14:37.371239,2026-08-17 10:14:38.015945,0 days 00:00:00.644706,7.799716,None,NaN,linear,COMPLETE

In [14]:
vis.plot_optimization_history(study)

In [15]:
vis.plot_param_importances(study)

In [16]:
vis.plot_parallel_coordinate(study)

# Szukanie hiperparametrów dla MLP

In [17]:
def mlp_search(trial):
  layer_options = {
        '32': (32,),
        '32_16': (32, 16),
        '64': (64,),
        '64_32': (64, 32),
        '128_64': (128, 64),
        '128_64_32': (128, 64, 32)
    }

  layer_name = trial.suggest_categorical('hidden_layer_sizes', list(layer_options.keys()))
  hidden_layer_sizes = layer_options[layer_name]

  activation = trial.suggest_categorical('activation', ['relu', 'tanh'])

  alpha = trial.suggest_float('alpha', 0.00001, 0.1, log=True)
  learning_rate_init = trial.suggest_float('learning_rate_init', 0.0001, 0.1, log=True)

  mlp = MLPClassifier(hidden_layer_sizes=hidden_layer_sizes, activation=activation, alpha=alpha,
                      learning_rate_init=learning_rate_init, max_iter=1000, random_state=42, early_stopping=True)

  pipeline = Pipeline([('scaler', StandardScaler()), ('mlp', mlp)])

  score = cross_val_score(pipeline, X, y, cv=5, scoring='f1').mean()

  return score

study = optuna.create_study(direction='maximize')

study.optimize(mlp_search, n_trials=100)

print("\n--- ZAKOŃCZONO ---")
print(f"Najlepszy F1: {study.best_value:.4f}")
print("Najlepsze parametry:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

[I 2026-08-17 10:15:17,298] A new study created in memory with name: no-name-429e1d71-5904-4f9e-80ee-db7f21e6f83a
[I 2026-08-17 10:15:27,825] Trial 0 finished with value: 0.7287478302117025 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'alpha': 0.025313891276822816, 'learning_rate_init': 0.0062518888311978195}. Best is trial 0 with value: 0.7287478302117025.
[I 2026-08-17 10:15:33,880] Trial 1 finished with value: 0.7193090823562598 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'alpha': 8.65722483047466e-05, 'learning_rate_init': 0.08026481112677171}. Best is trial 0 with value: 0.7287478302117025.
[I 2026-08-17 10:15:35,427] Trial 2 finished with value: 0.7495144214546577 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.0017314956540753208, 'learning_rate_init': 0.03607973706828513}. Best is trial 2 with value: 0.7495144214546577.
[I 2026-08-17 10:15:37,147] Trial 3 finished with value: 0.44884982924415506 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.0007229543732254723, 'learning_rate_init': 0.0002927420756730321}. Best is trial 2 with value: 0.7495144214546577.
[I 2026-08-17 10:15:38,256] Trial 4 finished with value: 0.0390418118466899 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'relu', 'alpha': 0.04945145589471094, 'learning_rate_init': 0.00011645506445633466}. Best is trial 2 with value: 0.7495144214546577.
[I 2026-08-17 10:15:44,136] Trial 5 finished with value: 0.7354662856859892 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 0.003029676753477219, 'learning_rate_init': 0.006202942079669911}. Best is trial 2 with value: 0.7495144214546577.
[I 2026-08-17 10:15:44,933] Trial 6 finished with value: 0.7309363661198347 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'relu', 'alpha': 0.001209540866103765, 'learning_rate_init': 0.019245514820030053}. Best is trial 2 with value: 0.7495144214546577.
[I 2026-08-17 10:15:56,978] Trial 7 finished with value: 0.7135623257336982 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 0.00014622055889423029, 'learning_rate_init': 0.04875104158345366}. Best is trial 2 with value: 0.7495144214546577.
[I 2026-08-17 10:15:58,581] Trial 8 finished with value: 0.754143870314083 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'alpha': 5.008336427008623e-05, 'learning_rate_init': 0.004881588706954774}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:15:59,370] Trial 9 finished with value: 0.7475236436595261 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'tanh', 'alpha': 0.006531421624526293, 'learning_rate_init': 0.019567474037680877}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:00,215] Trial 10 finished with value: 0.7216729323834563 and parameters: {'hidden_layer_sizes': '64_32', 'activation': 'tanh', 'alpha': 2.870696062734454e-05, 'learning_rate_init': 0.0008069584036830551}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:00,625] Trial 11 finished with value: 0.742644044733597 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 1.0936744776841446e-05, 'learning_rate_init': 0.0036580451543505813}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:01,072] Trial 12 finished with value: 0.7313479044406451 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.0002878846590222865, 'learning_rate_init': 0.001737675021306022}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:01,732] Trial 13 finished with value: 0.7502935569745406 and parameters: {'hidden_layer_sizes': '64', 'activation': 'tanh', 'alpha': 0.005436448106777042, 'learning_rate_init': 0.014870486204384319}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:05,578] Trial 14 finished with value: 0.7414563355051588 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'alpha': 0.017915922953332625, 'learning_rate_init': 0.012103282721705258}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:06,333] Trial 15 finished with value: 0.7085880619690769 and parameters: {'hidden_layer_sizes': '32', 'activation': 'tanh', 'alpha': 5.2160726314263685e-05, 'learning_rate_init': 0.0017194839571456808}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:07,712] Trial 16 finished with value: 0.7419971082801097 and parameters: {'hidden_layer_sizes': '64_32', 'activation': 'tanh', 'alpha': 0.00029849432665298597, 'learning_rate_init': 0.0023564193853020604}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:08,333] Trial 17 finished with value: 0.6604556873078613 and parameters: {'hidden_layer_sizes': '64', 'activation': 'tanh', 'alpha': 0.008006240877589166, 'learning_rate_init': 0.0007239532209473478}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:10,074] Trial 18 finished with value: 0.7378381392922446 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'alpha': 0.07936268145407738, 'learning_rate_init': 0.009569426832082282}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:10,706] Trial 19 finished with value: 0.7379032503662681 and parameters: {'hidden_layer_sizes': '64', 'activation': 'tanh', 'alpha': 1.286096497442315e-05, 'learning_rate_init': 0.027150441371211545}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:12,614] Trial 20 finished with value: 0.7149349880842868 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'alpha': 0.0005129394957354603, 'learning_rate_init': 0.09339450625290638}. Best is trial 8 with value: 0.754143870314083.
[I 2026-08-17 10:16:12,953] Trial 21 finished with value: 0.7677704220303927 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.0018624552032924246, 'learning_rate_init': 0.04348572082734197}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:13,277] Trial 22 finished with value: 0.7478760271739904 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.0069457669666187875, 'learning_rate_init': 0.012852077909081393}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:13,595] Trial 23 finished with value: 0.7526915963722711 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.003155146549867174, 'learning_rate_init': 0.05376618797860086}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:13,894] Trial 24 finished with value: 0.7548948437069161 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.0023458076635612356, 'learning_rate_init': 0.054130842240846515}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:14,207] Trial 25 finished with value: 0.7501795015654824 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 0.0011772371339849555, 'learning_rate_init': 0.037113821951349005}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:14,615] Trial 26 finished with value: 0.716369421686627 and parameters: {'hidden_layer_sizes': '64_32', 'activation': 'relu', 'alpha': 0.0001896312338702892, 'learning_rate_init': 0.060962275449392346}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:15,472] Trial 27 finished with value: 0.7592412600045308 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 3.06908570945902e-05, 'learning_rate_init': 0.006366795910915484}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:16,353] Trial 28 finished with value: 0.7527241822001101 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.01649677693136154, 'learning_rate_init': 0.02728826577024333}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:17,262] Trial 29 finished with value: 0.7594529883710839 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0006296715305825235, 'learning_rate_init': 0.007787629685748098}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:18,932] Trial 30 finished with value: 0.7444404533867844 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 2.294303089930381e-05, 'learning_rate_init': 0.0034117748324465776}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:22,959] Trial 31 finished with value: 0.7581801084190729 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0026163449368083575, 'learning_rate_init': 0.007887950352750101}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:24,265] Trial 32 finished with value: 0.757346340789036 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0007303646584777603, 'learning_rate_init': 0.0077091520114697595}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:25,192] Trial 33 finished with value: 0.7628512435925539 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0015849850796859626, 'learning_rate_init': 0.006570657053463894}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:26,259] Trial 34 finished with value: 0.7607078950897561 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0001010580093625325, 'learning_rate_init': 0.004131911350471194}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:27,716] Trial 35 finished with value: 0.7383830673143651 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0004699373033790005, 'learning_rate_init': 0.0009189980655402202}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:28,670] Trial 36 finished with value: 0.743399274317809 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0013051403187614068, 'learning_rate_init': 0.003580326196276612}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:30,069] Trial 37 finished with value: 0.7669533478476478 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 9.791173863995303e-05, 'learning_rate_init': 0.002301166519345695}. Best is trial 21 with value: 0.7677704220303927.
[I 2026-08-17 10:16:31,371] Trial 38 finished with value: 0.7727509221881801 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 9.821794250838439e-05, 'learning_rate_init': 0.0016994335383758432}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:33,429] Trial 39 finished with value: 0.7478109561953692 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 8.43536513299447e-05, 'learning_rate_init': 0.0004388991743692065}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:34,242] Trial 40 finished with value: 0.7217832144351807 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'relu', 'alpha': 0.00021714902034021565, 'learning_rate_init': 0.0012339679463208748}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:40,272] Trial 41 finished with value: 0.7514619309494296 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 8.357755433156812e-05, 'learning_rate_init': 0.0026783691065702902}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:41,788] Trial 42 finished with value: 0.5184669430111344 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0001014532911696403, 'learning_rate_init': 0.0001730438821555192}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:42,719] Trial 43 finished with value: 0.7653805561158034 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0001376892365958776, 'learning_rate_init': 0.004613202934662958}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:44,161] Trial 44 finished with value: 0.7697252653699806 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 5.556866860468277e-05, 'learning_rate_init': 0.0017382887503869392}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:44,523] Trial 45 finished with value: 0.6643511556669451 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 6.023565129098985e-05, 'learning_rate_init': 0.0014498237405589905}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:45,290] Trial 46 finished with value: 0.6932359258062697 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'relu', 'alpha': 1.8273999764117545e-05, 'learning_rate_init': 0.0005288388935280277}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:46,580] Trial 47 finished with value: 0.7666380890742399 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00013711869964816835, 'learning_rate_init': 0.002380112204584859}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:47,204] Trial 48 finished with value: 0.7355765203972107 and parameters: {'hidden_layer_sizes': '64_32', 'activation': 'relu', 'alpha': 3.986561791000493e-05, 'learning_rate_init': 0.0021647804366957384}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:48,615] Trial 49 finished with value: 0.7544810626352028 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0002924942883819106, 'learning_rate_init': 0.0011109943794908094}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:52,648] Trial 50 finished with value: 0.7306157105169717 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00015032533408125155, 'learning_rate_init': 0.00031135558590277115}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:56,298] Trial 51 finished with value: 0.7669145310191556 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00013054813635374023, 'learning_rate_init': 0.0017285421885221833}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:57,566] Trial 52 finished with value: 0.7678054186250908 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 6.087244958464384e-05, 'learning_rate_init': 0.001858223333352486}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:16:59,159] Trial 53 finished with value: 0.7464211305975466 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 4.804253839747808e-05, 'learning_rate_init': 0.0006531074343166383}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:00,464] Trial 54 finished with value: 0.7643341233035532 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 6.991714509823265e-05, 'learning_rate_init': 0.0017766061120275325}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:01,604] Trial 55 finished with value: 0.723531672284628 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'alpha': 3.270380280403768e-05, 'learning_rate_init': 0.0011083888497727392}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:02,092] Trial 56 finished with value: 0.7328252248809815 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.0003761622668230993, 'learning_rate_init': 0.002797777289916497}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:02,442] Trial 57 finished with value: 0.6718035383748023 and parameters: {'hidden_layer_sizes': '32', 'activation': 'relu', 'alpha': 1.3270905926185119e-05, 'learning_rate_init': 0.0015430198254369745}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:02,749] Trial 58 finished with value: 0.0390418118466899 and parameters: {'hidden_layer_sizes': '32_16', 'activation': 'relu', 'alpha': 3.853558133655922e-05, 'learning_rate_init': 0.00012242481370181087}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:03,322] Trial 59 finished with value: 0.7334221947746729 and parameters: {'hidden_layer_sizes': '64_32', 'activation': 'relu', 'alpha': 1.876914193454193e-05, 'learning_rate_init': 0.0018250419213637604}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:03,768] Trial 60 finished with value: 0.7221991619376213 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.00020488453744024258, 'learning_rate_init': 0.0008841418502687568}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:05,154] Trial 61 finished with value: 0.7668382867158191 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00011851395050765661, 'learning_rate_init': 0.002166265695541778}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:08,058] Trial 62 finished with value: 0.7527670639578818 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.00011102201469325163, 'learning_rate_init': 0.003030675258083031}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:14,524] Trial 63 finished with value: 0.7658852465366406 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 5.390884402379939e-05, 'learning_rate_init': 0.0013001700752331448}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:15,837] Trial 64 finished with value: 0.7662344472919299 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.03848327770823317, 'learning_rate_init': 0.0021396495010850246}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:16,760] Trial 65 finished with value: 0.7594986565099884 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0001737349770402377, 'learning_rate_init': 0.005158756123557819}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:18,840] Trial 66 finished with value: 0.7331084837616993 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'alpha': 6.791594974077497e-05, 'learning_rate_init': 0.0006192821296679941}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:20,137] Trial 67 finished with value: 0.7674369334917099 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0002539817791886054, 'learning_rate_init': 0.001939035510075491}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:20,490] Trial 68 finished with value: 0.7490397225925759 and parameters: {'hidden_layer_sizes': '64', 'activation': 'relu', 'alpha': 0.00027160521393869636, 'learning_rate_init': 0.017899524312499353}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:23,103] Trial 69 finished with value: 0.7500068821803509 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0008049595920366327, 'learning_rate_init': 0.000998540249739203}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:28,123] Trial 70 finished with value: 0.7378535081707105 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'tanh', 'alpha': 0.0043855536532179905, 'learning_rate_init': 0.0014675625035367322}. Best is trial 38 with value: 0.7727509221881801.
[I 2026-08-17 10:17:29,448] Trial 71 finished with value: 0.7667105281141419 and parameters: {'hidden_layer_sizes': '128_64_32', 'activation': 'relu', 'alpha': 0.0001090845420628873, 'learning_rate_init': 0.0018533304396993171}. Best is trial 38 with value: 0.7727509221881801.

--- ZAKOŃCZONO ---
Najlepszy F1: 0.7746
Najlepsze parametry:
  hidden_layer_sizes: 128_64_32
  activation: relu
  alpha: 9.093391502124464e-05
  learning_rate_init: 0.0017130453864760537

In [18]:
study.trials_dataframe().sort_values(by='value', ascending=False).head(10)

,number,value,datetime_start,datetime_complete,duration,params_activation,params_alpha,params_hidden_layer_sizes,params_learning_rate_init,state
82,82,0.774609,2026-08-17 10:17:43.769802,2026-08-17 10:17:45.064805,0 days 00:00:01.295003,relu,0.000091,128_64_32,0.001713,COMPLETE
92,92,0.774586,2026-08-17 10:18:00.433411,2026-08-17 10:18:01.796179,0 days 00:00:01.362768,relu,0.000043,128_64_32,0.001675,COMPLETE
38,38,0.772751,2026-08-17 10:16:30.071060,2026-08-17 10:16:31.371806,0 days 00:00:01.300746,relu,0.000098,128_64_32,0.001699,COMPLETE
96,96,0.771518,2026-08-17 10:18:06.033196,2026-08-17 10:18:07.249487,0 days 00:00:01.216291,relu,0.000036,128_64_32,0.001997,COMPLETE
81,81,0.770632,2026-08-17 10:17:39.495671,2026-08-17 10:17:43.768120,0 days 00:00:04.272449,relu,0.000097,128_64_32,0.001606,COMPLETE
95,95,0.770079,2026-08-17 10:18:04.722800,2026-08-17 10:18:06.030180,0 days 00:00:01.307380,relu,0.000069,128_64_32,0.002018,COMPLETE
44,44,0.769725,2026-08-17 10:16:42.724104,2026-08-17 10:16:44.161653,0 days 00:00:01.437549,relu,0.000056,128_64_32,0.001738,COMPLETE
84,84,0.768506,2026-08-17 10:17:46.532570,2026-08-17 10:17:48.029823,0 days 00:00:01.497253,relu,0.000069,128_64_32,0.001582,COMPLETE
52,52,0.767805,2026-08-17 10:16:56.300795,2026-08-17 10:16:57.566070,0 days 00:00:01.265275,relu,0.000061,128_64_32,0.001858,COMPLETE
21,21,0.767770,2026-08-17 10:16:12.617334,2026-08-17 10:16:12.953583,0 days 00:00:00.336249,relu,0.001862,64,0.043486,COMPLETE

In [19]:
vis.plot_optimization_history(study)

In [20]:
vis.plot_param_importances(study)

In [21]:
vis.plot_parallel_coordinate(study)

# Szukanie hiperparametrów dla KNN

In [22]:
def knn_search(trial):
  n_neighbors = trial.suggest_int('n_neighbors', 1, 50)

  weights = trial.suggest_categorical('weights', ['uniform', 'distance'])

  metric = trial.suggest_categorical('metric', ['euclidean', 'manhattan', 'cosine'])

  knn = KNeighborsClassifier(n_neighbors=n_neighbors, weights=weights, metric=metric)

  pipeline = Pipeline([('scaler', StandardScaler()), ('knn', knn)])

  score = cross_val_score(pipeline, X, y, cv=5, scoring='f1').mean()
  return score

study = optuna.create_study(direction='maximize')

study.optimize(knn_search, n_trials=100)

print("\n--- ZAKOŃCZONO ---")
print(f"Najlepszy F1: {study.best_value:.4f}")
print("Najlepsze parametry:")
for key, value in study.best_params.items():
    print(f"  {key}: {value}")

[I 2026-08-17 10:18:15,502] A new study created in memory with name: no-name-2464fbb2-84b0-432c-a2b4-9c05972ce16d
[I 2026-08-17 10:18:15,605] Trial 0 finished with value: 0.7237116529107894 and parameters: {'n_neighbors': 33, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 0 with value: 0.7237116529107894.
[I 2026-08-17 10:18:15,744] Trial 1 finished with value: 0.7210588429508726 and parameters: {'n_neighbors': 35, 'weights': 'uniform', 'metric': 'cosine'}. Best is trial 0 with value: 0.7237116529107894.
[I 2026-08-17 10:18:15,889] Trial 2 finished with value: 0.6979627530343911 and parameters: {'n_neighbors': 47, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 0 with value: 0.7237116529107894.
[I 2026-08-17 10:18:15,966] Trial 3 finished with value: 0.7388167509436949 and parameters: {'n_neighbors': 41, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 3 with value: 0.7388167509436949.
[I 2026-08-17 10:18:16,071] Trial 4 finished with value: 0.7202632994921896 and parameters: {'n_neighbors': 24, 'weights': 'uniform', 'metric': 'cosine'}. Best is trial 3 with value: 0.7388167509436949.
[I 2026-08-17 10:18:16,170] Trial 5 finished with value: 0.7381397317722864 and parameters: {'n_neighbors': 42, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 3 with value: 0.7388167509436949.
[I 2026-08-17 10:18:16,237] Trial 6 finished with value: 0.7188235434569276 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 3 with value: 0.7388167509436949.
[I 2026-08-17 10:18:16,312] Trial 7 finished with value: 0.7014726798625104 and parameters: {'n_neighbors': 40, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 3 with value: 0.7388167509436949.
[I 2026-08-17 10:18:16,387] Trial 8 finished with value: 0.7144172739887438 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 3 with value: 0.7388167509436949.
[I 2026-08-17 10:18:16,467] Trial 9 finished with value: 0.7379552288342556 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 3 with value: 0.7388167509436949.
[I 2026-08-17 10:18:16,538] Trial 10 finished with value: 0.7467260875584374 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 10 with value: 0.7467260875584374.
[I 2026-08-17 10:18:16,607] Trial 11 finished with value: 0.7467260875584374 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 10 with value: 0.7467260875584374.
[I 2026-08-17 10:18:16,681] Trial 12 finished with value: 0.7491171461577957 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 12 with value: 0.7491171461577957.
[I 2026-08-17 10:18:16,767] Trial 13 finished with value: 0.7491171461577957 and parameters: {'n_neighbors': 19, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 12 with value: 0.7491171461577957.
[I 2026-08-17 10:18:16,837] Trial 14 finished with value: 0.7325012138547518 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 12 with value: 0.7491171461577957.
[I 2026-08-17 10:18:16,926] Trial 15 finished with value: 0.7426760505123203 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 12 with value: 0.7491171461577957.
[I 2026-08-17 10:18:16,996] Trial 16 finished with value: 0.7410560510564397 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 12 with value: 0.7491171461577957.
[I 2026-08-17 10:18:17,071] Trial 17 finished with value: 0.7324909106116783 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 12 with value: 0.7491171461577957.
[I 2026-08-17 10:18:17,166] Trial 18 finished with value: 0.7219206081346699 and parameters: {'n_neighbors': 25, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 12 with value: 0.7491171461577957.
[I 2026-08-17 10:18:17,275] Trial 19 finished with value: 0.6883444126652545 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 12 with value: 0.7491171461577957.
[I 2026-08-17 10:18:17,350] Trial 20 finished with value: 0.7467260875584374 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 12 with value: 0.7491171461577957.
[I 2026-08-17 10:18:17,423] Trial 21 finished with value: 0.7467260875584374 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 12 with value: 0.7491171461577957.
[I 2026-08-17 10:18:17,498] Trial 22 finished with value: 0.7493319313097163 and parameters: {'n_neighbors': 29, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 22 with value: 0.7493319313097163.
[I 2026-08-17 10:18:17,574] Trial 23 finished with value: 0.750459264632543 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 23 with value: 0.750459264632543.
[I 2026-08-17 10:18:17,651] Trial 24 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:17,729] Trial 25 finished with value: 0.7515281238308986 and parameters: {'n_neighbors': 32, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:17,824] Trial 26 finished with value: 0.7231794114721777 and parameters: {'n_neighbors': 34, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:17,904] Trial 27 finished with value: 0.7466176108340365 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:17,990] Trial 28 finished with value: 0.7445266172483833 and parameters: {'n_neighbors': 29, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:18,088] Trial 29 finished with value: 0.7237116529107894 and parameters: {'n_neighbors': 32, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:18,199] Trial 30 finished with value: 0.7226201659133593 and parameters: {'n_neighbors': 49, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:18,300] Trial 31 finished with value: 0.7493319313097163 and parameters: {'n_neighbors': 29, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:18,379] Trial 32 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:18,462] Trial 33 finished with value: 0.7457098650770637 and parameters: {'n_neighbors': 36, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:18,543] Trial 34 finished with value: 0.7249826789515982 and parameters: {'n_neighbors': 32, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:18,615] Trial 35 finished with value: 0.7461199617665446 and parameters: {'n_neighbors': 26, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:18,728] Trial 36 finished with value: 0.7156067721736147 and parameters: {'n_neighbors': 39, 'weights': 'uniform', 'metric': 'cosine'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:18,847] Trial 37 finished with value: 0.7382645262660361 and parameters: {'n_neighbors': 44, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:18,928] Trial 38 finished with value: 0.7515281238308986 and parameters: {'n_neighbors': 32, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,007] Trial 39 finished with value: 0.6940084859638072 and parameters: {'n_neighbors': 44, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,082] Trial 40 finished with value: 0.7484268410031351 and parameters: {'n_neighbors': 23, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,153] Trial 41 finished with value: 0.7515281238308986 and parameters: {'n_neighbors': 32, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,226] Trial 42 finished with value: 0.7463401700999449 and parameters: {'n_neighbors': 34, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,303] Trial 43 finished with value: 0.7438554685066858 and parameters: {'n_neighbors': 38, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,377] Trial 44 finished with value: 0.7515281238308986 and parameters: {'n_neighbors': 32, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,449] Trial 45 finished with value: 0.7461199617665446 and parameters: {'n_neighbors': 26, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,539] Trial 46 finished with value: 0.7479840421016892 and parameters: {'n_neighbors': 35, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,610] Trial 47 finished with value: 0.7484268410031351 and parameters: {'n_neighbors': 23, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,692] Trial 48 finished with value: 0.7309829178782026 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,790] Trial 49 finished with value: 0.719522740033689 and parameters: {'n_neighbors': 42, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,901] Trial 50 finished with value: 0.7493066643129044 and parameters: {'n_neighbors': 27, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:19,983] Trial 51 finished with value: 0.746361022982856 and parameters: {'n_neighbors': 33, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,057] Trial 52 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,135] Trial 53 finished with value: 0.7457098650770637 and parameters: {'n_neighbors': 36, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,208] Trial 54 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,284] Trial 55 finished with value: 0.7420392707651191 and parameters: {'n_neighbors': 24, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,359] Trial 56 finished with value: 0.750459264632543 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,448] Trial 57 finished with value: 0.7428758259284576 and parameters: {'n_neighbors': 40, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,524] Trial 58 finished with value: 0.7493066643129044 and parameters: {'n_neighbors': 27, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,607] Trial 59 finished with value: 0.7452921637845004 and parameters: {'n_neighbors': 35, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,687] Trial 60 finished with value: 0.7230097926846433 and parameters: {'n_neighbors': 22, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,759] Trial 61 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,830] Trial 62 finished with value: 0.750459264632543 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:20,908] Trial 63 finished with value: 0.7493319313097163 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,007] Trial 64 finished with value: 0.7463401700999449 and parameters: {'n_neighbors': 34, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,088] Trial 65 finished with value: 0.7466176108340365 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,179] Trial 66 finished with value: 0.7408708200012548 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,279] Trial 67 finished with value: 0.7259670426288656 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,384] Trial 68 finished with value: 0.746361022982856 and parameters: {'n_neighbors': 33, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,465] Trial 69 finished with value: 0.7461199617665446 and parameters: {'n_neighbors': 26, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,541] Trial 70 finished with value: 0.750459264632543 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,620] Trial 71 finished with value: 0.7515281238308986 and parameters: {'n_neighbors': 32, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,707] Trial 72 finished with value: 0.746361022982856 and parameters: {'n_neighbors': 33, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,786] Trial 73 finished with value: 0.7457098650770637 and parameters: {'n_neighbors': 36, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,861] Trial 74 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:21,937] Trial 75 finished with value: 0.7493319313097163 and parameters: {'n_neighbors': 29, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,028] Trial 76 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,108] Trial 77 finished with value: 0.725146754199246 and parameters: {'n_neighbors': 25, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,210] Trial 78 finished with value: 0.719376754632229 and parameters: {'n_neighbors': 38, 'weights': 'distance', 'metric': 'cosine'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,305] Trial 79 finished with value: 0.7493319313097163 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,393] Trial 80 finished with value: 0.7408708200012548 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,466] Trial 81 finished with value: 0.7463401700999449 and parameters: {'n_neighbors': 34, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,542] Trial 82 finished with value: 0.750459264632543 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,617] Trial 83 finished with value: 0.7452921637845004 and parameters: {'n_neighbors': 35, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,694] Trial 84 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,764] Trial 85 finished with value: 0.7493066643129044 and parameters: {'n_neighbors': 27, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,835] Trial 86 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,908] Trial 87 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:22,981] Trial 88 finished with value: 0.7463401700999449 and parameters: {'n_neighbors': 34, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:23,077] Trial 89 finished with value: 0.74113751570095 and parameters: {'n_neighbors': 29, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:23,149] Trial 90 finished with value: 0.745467596121067 and parameters: {'n_neighbors': 25, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:23,224] Trial 91 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:23,303] Trial 92 finished with value: 0.746361022982856 and parameters: {'n_neighbors': 33, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:23,376] Trial 93 finished with value: 0.7525459355357332 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.
[I 2026-08-17 10:18:23,449] Trial 94 finished with value: 0.7493319313097163 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 24 with value: 0.7525459355357332.

--- ZAKOŃCZONO ---
Najlepszy F1: 0.7525
Najlepsze parametry:
  n_neighbors: 31
  weights: distance
  metric: euclidean

In [23]:
study.trials_dataframe().sort_values(by='value', ascending=False).head(10)

,number,value,datetime_start,datetime_complete,duration,params_metric,params_n_neighbors,params_weights,state
24,24,0.752546,2026-08-17 10:18:17.575247,2026-08-17 10:18:17.651632,0 days 00:00:00.076385,euclidean,31,distance,COMPLETE
32,32,0.752546,2026-08-17 10:18:18.304916,2026-08-17 10:18:18.379435,0 days 00:00:00.074519,euclidean,31,distance,COMPLETE
61,61,0.752546,2026-08-17 10:18:20.688421,2026-08-17 10:18:20.759852,0 days 00:00:00.071431,euclidean,31,distance,COMPLETE
54,54,0.752546,2026-08-17 10:18:20.136333,2026-08-17 10:18:20.208773,0 days 00:00:00.072440,euclidean,31,distance,COMPLETE
74,74,0.752546,2026-08-17 10:18:21.787959,2026-08-17 10:18:21.861725,0 days 00:00:00.073766,euclidean,31,distance,COMPLETE
76,76,0.752546,2026-08-17 10:18:21.938992,2026-08-17 10:18:22.028383,0 days 00:00:00.089391,euclidean,31,distance,COMPLETE
86,86,0.752546,2026-08-17 10:18:22.765299,2026-08-17 10:18:22.835068,0 days 00:00:00.069769,euclidean,31,distance,COMPLETE
93,93,0.752546,2026-08-17 10:18:23.304693,2026-08-17 10:18:23.376396,0 days 00:00:00.071703,euclidean,31,distance,COMPLETE
91,91,0.752546,2026-08-17 10:18:23.150698,2026-08-17 10:18:23.224525,0 days 00:00:00.073827,euclidean,31,distance,COMPLETE
52,52,0.752546,2026-08-17 10:18:19.984972,2026-08-17 10:18:20.057529,0 days 00:00:00.072557,euclidean,31,distance,COMPLETE

In [24]:
vis.plot_optimization_history(study)

In [25]:
vis.plot_param_importances(study)

In [26]:
vis.plot_parallel_coordinate(study)

# Moje szanse na tytaniku 💀

In [27]:
print(titanic_df.columns)
titanic_df.head()

Index(['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'FamilySize', 'IsAlone',
       'Embarked_Q', 'Embarked_S', 'Cabin_B', 'Cabin_C', 'Cabin_D', 'Cabin_E',
       'Cabin_F', 'Cabin_G', 'Cabin_T', 'Cabin_Unknown', 'Title_Miss',
       'Title_Mr', 'Title_Mrs', 'Title_Rare'],
      dtype='object')

,Survived,Pclass,Sex,Age,Fare,FamilySize,IsAlone,Embarked_Q,Embarked_S,Cabin_B,...,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Cabin_Unknown,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
PassengerId,,,,,,,,,,,,,,,,,,,,,
1,0,3,0,22.0,7.2500,2,0,0,1,0,...,0,0,0,0,0,1,0,1,0,0
2,1,1,1,38.0,71.2833,2,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,3,1,26.0,7.9250,1,1,0,1,0,...,0,0,0,0,0,1,1,0,0,0
4,1,1,1,35.0,53.1000,2,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
5,0,3,0,35.0,8.0500,1,1,0,1,0,...,0,0,0,0,0,1,0,1,0,0

In [28]:
ja = pd.DataFrame([{
    'Pclass': 1,
    'Sex': 0,
    'Age': 21.0,
    'Fare': 53.0,
    'FamilySize': 2,
    'IsAlone': 0,
    'Embarked_Q': 1,
    'Embarked_S': 0,
    'Cabin_B': 0,
    'Cabin_C': 0,
    'Cabin_D': 0,
    'Cabin_E': 0,
    'Cabin_F': 0,
    'Cabin_G': 0,
    'Cabin_T': 0,
    'Cabin_Unknown': 0,
    'Title_Miss': 0,
    'Title_Mr': 1,
    'Title_Mrs': 0,
    'Title_Rare': 0
}])

# użyje dobrych parametrów
  # * wartości mogą się różnić bo raczej odpale cały plik jak skończę
svm = SVC(kernel='rbf', C=7.925165, gamma=0.012747, class_weight=None)
svm.fit(X_train_scaled, y_train)

mlp = MLPClassifier(max_iter=1000, random_state=42, hidden_layer_sizes=(128, 64, 32), alpha=0.000312, learning_rate_init=0.001695, early_stopping=True)
mlp.fit(X_train_scaled, y_train)

knn = KNeighborsClassifier(n_neighbors=31, metric='euclidean', weights='distance')
knn.fit(X_train_scaled, y_train)

ja_scaled = scaler.transform(ja)

svm_pred = svm.predict(ja_scaled)
mlp_pred = mlp.predict(ja_scaled)
knn_pred = knn.predict(ja_scaled)

for pred in [svm_pred, mlp_pred, knn_pred]:
  if pred[0] == 1:
    print('Żyje!!!')
  else:
    print('GG')

GG
Żyje!!!
GG

# Wnioski
* niestety wygląda na to, że nie przeżyłbym na tytaniku, a przynajmniej 2 na 3 modele tak zdecydowały (mimo, że dałem sobie 1 klasę)
* wszystkie 3 modele pokonały model bazowy
* wszystkie 3 modele osiągnęły bardzo podobny poziom
* poprawność przewidywania jest znacząco zależna od tego jakie dane wylosują się jako treningowe